import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { AppProvider } from "@/provider/app-provider";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });
const Hello = dynamic(() => import("@/modules/Hello/Hello"), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            <AppProvider>
              <Hello />
            </AppProvider>
          </p>
        </div>
      </main>
    </>
  );
}
